<?php

namespace App\Models;

//use App\Model;
use Illuminate\Database\Eloquent\Model;
//use Illuminate\Database\Eloquent\Factories\HasFactory;

class Discussion extends Model
{
    protected $guarded = [];

    public function author(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }
//    use HasFactory;

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function markAsBestReply(Reply $reply){
        $this->update([
            'reply_id' => $reply->id
        ]);
    }

//    public function getBestReply(){
//        return Reply::find($this->reply_id);
//    }

    public function BestReply(){
        return $this->belongsTo(Reply::class, 'reply_id');
    }

    protected $fillable = ['title','content','user_id','channel_id', 'slug'];

    public function channel(){
        return $this->belongsTo(Channel::class);
    }
}


